version: '3.1'
services:
  postgres_app:
    container_name: postgres_ApiNodeAuth
    hostname: db_apiNodeAuth
    image: postgres:latest
    volumes:
      - C:\Users\Elias\Documents\BaseDeDados\Postgres\pg_apiNodeAuth:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: api_NodeAuth
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: America/Sao_Paulo
    networks:
      - mynetwork

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "node-api"
    command: npm run dev
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET: ${SECRET}
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
    depends_on:
      - postgres_app
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge 